app:
  name: 'question-service'
  version: '1.0.0'
http:
  port: '80'
  cert_file: ''
  key_file: ''
grpc:
  addr: ':50052'
  conn: ':50051'
redis:
  addr: ':6379'

logger:
  log_level: 'debug'
env: 'local'