services:
  question-service:
    build: .
    ports:
      - "8080:8080"
      - "50052:50052"
    depends_on:
      - redis
      - ml-service
    environment:
      REDIS_ADDR: redis:6379
      GRPC_CONNECTION: ml-service:50051
      HTTP_CERT_FILE: /etc/letsencrypt/live/4-gk.ru/fullchain.pem
      HTTP_KEY_FILE: /etc/letsencrypt/live/4-gk.ru/privkey.pem

    volumes:
      - ./config:/root/config

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  ml-service:
    image: ml-service:latest
    ports:
      - "50051:50051"
