version: '3.8'

services:
  question-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      REDIS_ADDR: redis:6379
    volumes:
      - ./config:/root/config

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
